# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Disk < Formula
  desc "Disk is a CLI tool that helps you identify files that you can remove."
  homepage "https://github.com/sebastianappelberg/disk"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sebastianappelberg/disk/releases/download/v0.4.0/disk_Darwin_x86_64.tar.gz"
      sha256 "2bf8597266b0cf862e0f04852ac073e6863a0d50fd021a8c43ced0dcd2a49d64"

      define_method(:install) do
        bin.install "disk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sebastianappelberg/disk/releases/download/v0.4.0/disk_Darwin_arm64.tar.gz"
      sha256 "51a54218cc447e26bc90ec0ee3d480ac272479dcd8aca2a97d6dedf128f09fa3"

      define_method(:install) do
        bin.install "disk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastianappelberg/disk/releases/download/v0.4.0/disk_Linux_x86_64.tar.gz"
      sha256 "8d4ba1f2483b701a8b7f63c1afb3ec593f1415f12a1a391840ffcc4fa40c7e60"
      define_method(:install) do
        bin.install "disk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastianappelberg/disk/releases/download/v0.4.0/disk_Linux_arm64.tar.gz"
      sha256 "23fa3e57023d52a8a0f70cafca0ab13869ea8d7d780fc84769dbe0228128e82f"
      define_method(:install) do
        bin.install "disk"
      end
    end
  end
end
